%% Obiekt inercyjny I rzędu
t = 0:0.1:20;
k = 5;
T = 3;
licz = [0, k];
mian = [T, 1];
y1 = step(licz, mian, t);
z1 = impulse(licz, mian, t);
f1 = figure();
subplot(2,2,[1,3]);
nyquist(licz, mian);
title('Wykres Nyquista');
xlabel('Oś rzeczywista');
ylabel('Oś urojona');
omega = logspace(-2, 2, 1000);
[A, F] = bode(licz, mian, omega);
A_db = 20*log10(A);
subplot(2,2,2);
semilogx(omega, A_db);
title('Wykres Bodego');
ylabel('Amplituda [dB]');
subplot(2,2,4);
semilogx(omega, F);
xlabel('Częstotliwość');
ylabel('Faza [stopnie]');
k = 4.5;
T = 5;
licz = [0, k];
mian = [T, 1];
y2 = step(licz, mian, t);
z2 = impulse(licz, mian, t);
f2 = figure();
subplot(2,2,[1,3]);
nyquist(licz, mian);
title('Wykres Nyquista');
xlabel('Oś rzeczywista');
ylabel('Oś urojona');
[A, F] = bode(licz, mian, omega);
A_db = 20*log10(A);
subplot(2,2,2);
semilogx(omega, A_db);
title('Wykres Bodego');
ylabel('Amplituda [dB]');
subplot(2,2,4);
semilogx(omega, F);
xlabel('Częstotliwość');
ylabel('Faza [stopnie]');
f3 = figure();
plot(t, y1, t, y2);
title('Step Response');
xlabel('Time (sec)');
ylabel('Amplitude');
legend('k = 5; T = 3', 'k = 4.5; T = 5');
f4 = figure();
plot(t, z1, t, z2);
title('Impulse Response');
xlabel('Time (sec)');
ylabel('Amplitude');
legend('k = 5; T = 3', 'k = 4.5; T = 5');
%% Obiekt inercyjny II rzędu
t = 0:0.1:20;
k = 9;
T1 = 1.5;
T2 = 6.5;
licz = [0, 0, k];
mian = [T1*T2, T1+T2, 1];
y1 = step(licz, mian, t);
z1 = impulse(licz, mian, t);
f5 = figure();
[Re, Im] = nyquist(licz, mian);
subplot(2,2,[1,3]);
plot(Re(:), Im(:));
title('Wykres Nyquista');
xlabel('Oś rzeczywista');
ylabel('Oś urojona');
omega = logspace(-2, 2, 1000);
[A, F] = bode(licz, mian, omega);
A_db = 20*log10(A);
subplot(2,2,2);
semilogx(omega, A_db);
title('Wykres Bodego');
ylabel('Amplituda [dB]');
subplot(2,2,4);
semilogx(omega, F);
xlabel('Częstotliwość');
ylabel('Faza [stopnie]');
k = 2;
T1 = 7;
T2 = 8.5;
licz = [0, 0, k];
mian = [T1*T2, T1+T2, 1];
y2 = step(licz, mian, t);
z2 = impulse(licz, mian, t);
f6 = figure();
[Re, Im] = nyquist(licz, mian);
subplot(2,2,[1,3]);
plot(Re(:), Im(:));
title('Wykres Nyquista');
xlabel('Oś rzeczywista');
ylabel('Oś urojona');
[A, F] = bode(licz, mian, omega);
A_db = 20*log10(A);
subplot(2,2,2);
semilogx(omega, A_db);
title('Wykres Bodego');
ylabel('Amplituda [dB]');
subplot(2,2,4);
semilogx(omega, F);
xlabel('Częstotliwość');
ylabel('Faza [stopnie]');
f7 = figure();
plot(t, y1, t, y2);
title('Step Response');
xlabel('Time (sec)');
ylabel('Amplitude');
legend('k = 9; T1 = 1.5; T2 = 6.5', 'k = 2; T1 = 7; T2 = 8.5');
f8 = figure();
plot(t, z1, t, z2);
title('Impulse Response');
xlabel('Time (sec)');
ylabel('Amplitude');
legend('k = 9; T1 = 1.5; T2 = 6.5', 'k = 2; T1 = 7; T2 = 8.5');
%% Obiekt inercyjny II rzędu (inna postać)
t = 0:0.1:20;
k = 6.5;
T = 7;
ksi = 2;
licz = [0, 0, k];
mian = [T^2, 2*ksi*T, 1];
y1 = step(licz, mian, t);
z1 = impulse(licz, mian, t);
f9 = figure();
sys = tf(licz, mian);
subplot(2,2,[1,3]);
h = nyquistplot(sys);
setoptions(h, 'ShowFullContour', 'off');
title('Wykres Nyquista');
xlabel('Oś rzeczywista');
ylabel('Oś urojona');
omega = logspace(-2, 2, 1000);
[A, F] = bode(licz, mian, omega);
A_db = 20*log10(A);
subplot(2,2,2);
semilogx(omega, A_db);
title('Wykres Bodego');
ylabel('Amplituda [dB]');
subplot(2,2,4);
semilogx(omega, F);
xlabel('Częstotliwość');
ylabel('Faza [stopnie]');
k = 9;
T = 2.25;
ksi = 0.5;
licz = [0, 0, k];
mian = [T^2, 2*ksi*T, 1];
y2 = step(licz, mian, t);
z2 = impulse(licz, mian, t);
f10 = figure();
sys = tf(licz, mian);
subplot(2,2,[1,3]);
h = nyquistplot(sys);
setoptions(h, 'ShowFullContour', 'off');
title('Wykres Nyquista');
xlabel('Oś rzeczywista');
ylabel('Oś urojona');
[A, F] = bode(licz, mian, omega);
A_db = 20*log10(A);
subplot(2,2,2);
semilogx(omega, A_db);
title('Wykres Bodego');
ylabel('Amplituda [dB]');
subplot(2,2,4);
semilogx(omega, F);
xlabel('Częstotliwość');
ylabel('Faza [stopnie]');
f11 = figure();
plot(t, y1, t, y2);
title('Step Response');
xlabel('Time (sec)');
ylabel('Amplitude');
legend('k = 6.5; T = 7; ksi = 2', 'k = 9; T = 2.25; ksi = 0.5');
f12 = figure();
plot(t, z1, t, z2);
title('Impulse Response');
xlabel('Time (sec)');
ylabel('Amplitude');
legend('k = 6.5; T = 7; ksi = 2', 'k = 9; T = 2.25; ksi = 0.5');
%% Obiekt całkujący rzeczywisty
t = 0:0.1:20;
k = 5.5;
T = 6;
Ti = 4;
licz = [0, 0, k];
mian = [T*Ti, Ti, 0];
y1 = step(licz, mian, t);
z1 = impulse(licz, mian, t);
f13 = figure();
subplot(2,2,[1,3]);
nyquist(licz, mian);
title('Wykres Nyquista');
xlabel('Oś rzeczywista');
ylabel('Oś urojona');
omega = logspace(-2, 2, 1000);
[A, F] = bode(licz, mian, omega);
A_db = 20*log10(A);
subplot(2,2,2);
semilogx(omega, A_db);
title('Wykres Bodego');
ylabel('Amplituda [dB]');
subplot(2,2,4);
semilogx(omega, F);
xlabel('Częstotliwość');
ylabel('Faza [stopnie]');
k = 8.25;
T = 3.25;
Ti = 5;
licz = [0, 0, k];
mian = [T*Ti, Ti, 0];
y2 = step(licz, mian, t);
z2 = impulse(licz, mian, t);
f14 = figure();
subplot(2,2,[1,3]);
nyquist(licz, mian);
title('Wykres Nyquista');
xlabel('Oś rzeczywista');
ylabel('Oś urojona');
[A, F] = bode(licz, mian, omega);
A_db = 20*log10(A);
subplot(2,2,2);
semilogx(omega, A_db);
title('Wykres Bodego');
ylabel('Amplituda [dB]');
subplot(2,2,4);
semilogx(omega, F);
xlabel('Częstotliwość');
ylabel('Faza [stopnie]');
f15 = figure();
plot(t, y1, t, y2);
title('Step Response');
xlabel('Time (sec)');
ylabel('Amplitude');
legend('k = 5.5; T = 6; Ti = 4', 'k = 8.25; T = 3.25; Ti = 5');
f16 = figure();
plot(t, z1, t, z2);
title('Impulse Response');
xlabel('Time (sec)');
ylabel('Amplitude');
legend('k = 5.5; T = 6; Ti = 4', 'k = 8.25; T = 3.25; Ti = 5');
%% Obiekt różniczkujący rzeczywisty
t = 0:0.1:20;
Td = 5.25;
T = 9;
licz = [Td, 0];
mian = [T, 1];
y1 = step(licz, mian, t);
z1 = impulse(licz, mian, t);
f17 = figure();
[Re, Im] = nyquist(licz, mian);
subplot(2,2,[1,3]);
plot(Re(:), Im(:));
title('Wykres Nyquista');
xlabel('Oś rzeczywista');
ylabel('Oś urojona');
omega = logspace(-2, 2, 1000);
[A, F] = bode(licz, mian, omega);
A_db = 20*log10(A);
subplot(2,2,2);
semilogx(omega, A_db);
title('Wykres Bodego');
ylabel('Amplituda [dB]');
subplot(2,2,4);
semilogx(omega, F);
xlabel('Częstotliwość');
ylabel('Faza [stopnie]');
Td = 8.5;
T = 5;
licz = [Td, 0];
mian = [T, 1];
y2 = step(licz, mian, t);
z2 = impulse(licz, mian, t);
f18 = figure();
[Re, Im] = nyquist(licz, mian);
subplot(2,2,[1,3]);
plot(Re(:), Im(:));
title('Wykres Nyquista');
xlabel('Oś rzeczywista');
ylabel('Oś urojona');
[A, F] = bode(licz, mian, omega);
A_db = 20*log10(A);
subplot(2,2,2);
semilogx(omega, A_db);
title('Wykres Bodego');
ylabel('Amplituda [dB]');
subplot(2,2,4);
semilogx(omega, F);
xlabel('Częstotliwość');
ylabel('Faza [stopnie]');
f19 = figure();
plot(t, y1, t, y2);
title('Step Response');
xlabel('Time (sec)');
ylabel('Amplitude');
legend('Td = 5.25; T = 9', 'Td = 8.5; T = 5');
f20 = figure();
plot(t, z1, t, z2);
title('Impulse Response');
xlabel('Time (sec)');
ylabel('Amplitude');
legend('Td = 5.25; T = 9', 'Td = 8.5; T = 5');
%% Obiekt inercyjny I rzędu z opóźnieniem
t = 0:0.1:20;
k = 9.5;
T = 3.25;
theta = 5;
n = 5;
licz_iner = [0, k];
mian_iner = [T, 1];
[licz_op, mian_op] = pade(theta, n);
[licz, mian] = series(licz_op, mian_op, licz_iner, mian_iner);
y1 = step(licz, mian, t);
z1 = impulse(licz, mian, t);
f21 = figure();
sys = tf(licz, mian);
subplot(2,2,[1,3]);
h = nyquistplot(sys);
setoptions(h, 'ShowFullContour', 'off');
title('Wykres Nyquista');
xlabel('Oś rzeczywista');
ylabel('Oś urojona');
omega = logspace(-2, 2, 1000);
[A, F] = bode(licz, mian, omega);
A_db = 20*log10(A);
subplot(2,2,2);
semilogx(omega, A_db);
title('Wykres Bodego');
ylabel('Amplituda [dB]');
subplot(2,2,4);
semilogx(omega, F);
xlabel('Częstotliwość');
ylabel('Faza [stopnie]');
k = 7;
T = 6;
theta = 8;
n = 5;
licz_iner = [0, k];
mian_iner = [T, 1];
[licz_op, mian_op] = pade(theta, n);
[licz, mian] = series(licz_op, mian_op, licz_iner, mian_iner);
y2 = step(licz, mian, t);
z2 = impulse(licz, mian, t);
f22 = figure();
sys = tf(licz, mian);
subplot(2,2,[1,3]);
h = nyquistplot(sys);
setoptions(h, 'ShowFullContour', 'off');
title('Wykres Nyquista');
xlabel('Oś rzeczywista');
ylabel('Oś urojona');
[A, F] = bode(licz, mian, omega);
A_db = 20*log10(A);
subplot(2,2,2);
semilogx(omega, A_db);
title('Wykres Bodego');
ylabel('Amplituda [dB]');
subplot(2,2,4);
semilogx(omega, F);
xlabel('Częstotliwość');
ylabel('Faza [stopnie]');
f23 = figure();
plot(t, y1, t, y2);
title('Step Response');
xlabel('Time (sec)');
ylabel('Amplitude');
legend('k = 9.5; T = 3.25; theta = 5; n = 5', 'k = 7; T = 6; theta = 8; n = 5');
f24 = figure();
plot(t, z1, t, z2);
title('Impulse Response');
xlabel('Time (sec)');
ylabel('Amplitude');
legend('k = 9.5; T = 3.25; theta = 5; n = 5', 'k = 7; T = 6; theta = 8; n = 5');
